programs:                           # REQUIRED
  process:                          # REQUIRED
    cmd: "command to execute"       # REQUIRED
    numprocs: 1                     # OPTIONAL, default: 1
    umask: 022                      # OPTIONAL, default: 022
    workingdir: /tmp                # OPTIONAL, default: ./      
    autostart: false                # OPTIONAL, default: false
    autorestart: unexpected         # OPTIONAL, default: unexpected
    exitcodes:                      # OPTIONAL, default: [0]
      - 0
      - 2
    startretries: 3                 # OPTIONAL, default: 0
    starttime: 30                   # OPTIONAL, default: 0
    stopsignal: TERM                # OPTIONAL, default: TERM
    stoptime: 10                    # OPTIONAL, default: 10
    stdout: /tmp/k3d.stdout         # OPTIONAL, default: stdout
    stderr: /tmp/k3d.stderr         # OPTIONAL, default: stderr
    env:                            # OPTIONAL, default: {}
      STARTED_BY: taskmaster
      ANSWER: 42