  sleep:
    cmd: "sleep 300"
    numprocs: 2
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: always
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  sleep:
    cmd: "sleep 300"
    numprocs: 2
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: always
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr