programs:
    yes:
        cmd: "yes 'infinite output 2'"
        numprocs: 4
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: yes.stdout
        stderr: yes.stderr
    err:
        cmd: "/bin/bash -c 'while true; do echo \"Error: $(date)\" >&2; sleep 0.1; done'"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: err.stdout
        stderr: err.stderr
    yes2:
        cmd: "yes 'other output"
        numprocs: 2
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: yes.stdout
        stderr: yes.stderr
