programs:
    yes:
        cmd: "yes 'infinite output'"
        numprocs: 4
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: yes.stdout
        stderr: yes.stderr
    err:
        cmd: "unknown command"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: err.stdout
        stderr: err.stderr
    yes2:
        cmd: "yes 'other output"
        numprocs: 2
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: yes.stdout
        stderr: yes.stderr

    chars:
        cmd: "yes 'test'"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: $!%*()/\
        stderr: ?><d3#

    wrong_path:
        cmd: "yes 'test'"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: /root/test.stdout
        stderr: /root/test.stderr

    notexist:
        cmd: "yes 'test'"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: dirnotexist/test.stdout
        stderr: dirnotexist/test.stderr
    dir:
        cmd: "yes 'test'"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: dir/test.stdout
        stderr: dir/test.stderr
    unwritable:
        cmd: "echo 'test'"
        numprocs: 1
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: 0.stdout
        stderr: 0.stderr