programs:
    sleep:
        cmd: "sleep 950"
        numprocs: 9
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: /tmp/sleep.stdout
        stderr: /tmp/sleep.stderr
    sleep2:
        cmd: "sleep 370"
        numprocs: 3
        umask: 077
        workingdir: /tmp
        autostart: false
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: /tmp/sleep.stdout
        stderr: /tmp/sleep.stderr
    sleep_autostart:
        cmd: "sleep 940"
        numprocs: 9
        umask: 077
        workingdir: /tmp
        autostart: true
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: /tmp/sleep.stdout
        stderr: /tmp/sleep.stderr
    sleep2_autostart:
        cmd: "sleep 360"
        numprocs: 3
        umask: 077
        workingdir: /tmp
        autostart: true
        autorestart: never
        exitcodes:
            - 0
            - 1
        startretries: 0
        starttime: 1
        stopsignal: TERM
        stoptime: 10
        stdout: /tmp/sleep.stdout
        stderr: /tmp/sleep.stderr
 