programs:
  k3d:
    cmd: "/usr/local/bin/k3d cluster start home-lab || echo $ANSWER"
    numprocs: 1
    umask: 022
    workingdir: /tmp
    autostart: false
    autorestart: unexpected
    exitcodes:
      - 0
      - 2
    startretries: 3
    starttime: 30
    stopsignal: TERM
    stoptime: 10
    stdout: /tmp/k3d.stdout
    stderr: /tmp/k3d.stderr
    env:
      STARTED_BY: taskmaster
      ANSWER: 42

  nginx:
    cmd: "/usr/sbin/nginx -c /etc/nginx/nginx.conf"
    numprocs: 1
    umask: 077
    workingdir: /tmp
    autostart: false
    autorestart: unexpected
    exitcodes:
      - 0
    startretries: 3
    starttime: 5
    stopsignal: USR1
    stoptime: 10
    stdout: /tmp/nginx.stdout
    stderr: /tmp/nginx.stderr

  sleep:
    cmd: "sleep 300"
    numprocs: 2
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: always
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  sleep2:
    cmd: "sleep 300"
    numprocs: 2
    umask: 077
    workingdir: /tmp
    autostart: true
    autorestart: always
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
