programs:
  umask_permissif:
    cmd: "sleep 300"
    numprocs: 2
    umask: 0000
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
  unmask_missing:
    cmd: "sleep 300"
    numprocs: 2
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
  unmask_overflow:
    cmd: "sleep 300"
    numprocs: 2
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
    umask: 999999999
  unmask_underflow:
    cmd: "sleep 300"
    numprocs: 2
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
    umask: -999999999
  unmask_format:
    cmd: "sleep 300"
    numprocs: 2
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: 
      - 0
      - 1
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
    umask: 0 7 0 7
  umask_min_ok:
    cmd: "sleep 300"
    numprocs: 1
    umask: 0
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  umask_typical_ok:
    cmd: "sleep 300"
    numprocs: 1
    umask: 0o022
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  umask_max_ok:
    cmd: "sleep 300"
    numprocs: 1
    umask: 0o777
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
  umask_above_max:
    cmd: "sleep 300"
    numprocs: 1
    umask: 0o1000
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  umask_decimal_too_big:
    cmd: "sleep 300"
    numprocs: 1
    umask: 777
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr
  umask_string:
    cmd: "sleep 300"
    numprocs: 1
    umask: "022"
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  umask_float:
    cmd: "sleep 300"
    numprocs: 1
    umask: 2.2
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr

  umask_bool:
    cmd: "sleep 300"
    numprocs: 1
    umask: true
    workingdir: /tmp
    autostart: true
    autorestart: never
    exitcodes: [0]
    startretries: 0
    starttime: 1
    stopsignal: HUP
    stoptime: 10
    stdout: /tmp/sleep.stdout
    stderr: /tmp/sleep.stderr